---
cluster_name: eks-sample
cluster_version: "1.20"
cidr_block: 10.50.0.0/16
private_subnets:
  - 10.50.1.0/24
  - 10.50.2.0/24
  - 10.50.3.0/24
public_subnets:
  - 10.50.4.0/24
  - 10.50.5.0/24
  - 10.50.6.0/24
aws_availability_zones: [""]
node_groups:
  eks-sample:
    desired_capacity: "1"
    max_capacity: "3"
    min_capacity: "1"
    ami_type: AL2_x86_64
    instance_types:
      - t3.small
    capacity_type: ON_DEMAND
cluster_enabled_log_types:
  - api
  - audit
  - authenticator
  - controllerManager
  - scheduler
users_list:
  - name: root-user
    role: root
tags:
  Project: VKPR
  Source: aws-eks
