name: init

on:
  workflow_run:
    workflows:
      - "backend"
    types:
      - completed

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan.cache
          key: terraform-lock-${{ steps.extract_branch.outputs.branch }}
      - name: Terraform Init
        id: init
        run: |
             cat main.tf 
             export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
             export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
             terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out plan.cache
      - name: encrypt cache
        run: zip --password "${{ secrets.ZIP_PASSWORD }}" plan.zip plan.cache
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: plan-file
          path: plan.zip
