name: init

on:
  workflow_run:
    workflows:
      - "backend"
    types:
      - completed

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: little-core-labs/install-terraform@v2.0.0
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan.cache
          key: terraform-lock-${{ steps.extract_branch.outputs.branch }}
      - name: Terraform Init
        id: init
        run: |
             export AWS_ACCESS_KEY_ID=AKIAQAU7HN2IO7PSWCXH
             export AWS_SECRET_ACCESS_KEY=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
             cat main.tf 
             terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out plan.cache
      - name: encrypt cache
        run: zip --password "${{ secrets.ZIP_PASSWORD }}" plan.zip plan.cache
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: plan-file
          path: plan.zip
